// DesafioMxM_FrontEnd/src/components/Form/Form.tsx
import styles from "./style.module.css";
import axios from "axios";
import { maskJs } from "mask-js";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Modal } from "../../utils/Modal/Modal";
import {
  cleanMask,
  applyCnpjMask,
  applyCpfMask,
  applyPhoneNumberMask,
  validateCpfOrCnpj,
  validateEmail,
  validatePhoneNumber,
} from "../../services/formServices";
import { Checkbox } from "../../utils/CheckBox/CheckBox";
import { FormInputs } from "../FormInputs/FormInputs";

export function Form() {
  const [selectedOption, setSelectedOption] = useState("Pessoa física");
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showModal, setShowModal] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    reset,
    formState: { errors },
  } = useForm();

  function modalHandler() {
    setShowModal(false);
  }

  function checkboxHandler(event: any) {
    setSelectedOption(event.target.value);
  }

  function valueBasedOnCpfOrCnpj(value1: any, value2: any) {
    return selectedOption === "Pessoa física" ? value1 : value2;
  }

  async function onSubmit(data: any) {
    try {
      const headers = {
        "Content-Type": "application/json",
      };
      data.type = selectedOption;
      data.legalId = cleanMask(data.legalId);
      data.phoneNumber = cleanMask(data.phoneNumber);
      data.postalCode = cleanMask(data.postalCode);

      setIsSubmitting(true);

      const response = await axios.post(
        "https://localhost:7042/users",
        JSON.stringify(data),
        {
          headers,
        }
      );
      console.log(response);
      setIsSubmitting(false);
      reset();
      setShowModal(true);
      //
    } catch (err) {
      console.error();
    }
  }

  async function postalCodeHandler(event: any) {
    try {
      const { value } = event.target;
      const postalCodeWithMask = maskJs("99999-999", value);
      event.target.value = postalCodeWithMask;
      const cleanValue = cleanMask(postalCodeWithMask);

      if (cleanValue.length == 8) {
        //O timer é apenas para poder mostrar o efeito do spinner
        setIsLoading(true);
        setTimeout(async () => {
          const response = await axios.get(
            `https://viacep.com.br/ws/${cleanValue}/json/`
          );

          const { logradouro, bairro, localidade, uf } = response.data;

          setValue("street", logradouro || "", { shouldValidate: false });
          setValue("neighborhood", bairro || "", { shouldValidate: false });
          setValue("city", localidade || "", { shouldValidate: false });
          setValue("state", uf || "", { shouldValidate: false });
          setIsLoading(false);
        }, 500);
      }
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div className='container'>
      <h2 className='title'>Cadastro de Usuario</h2>
      <Checkbox
        values={["Pessoa física", "Pessoa juridica"]}
        onChangeHandler={checkboxHandler}
        checkedStatusState={selectedOption}
      />
      <form onSubmit={handleSubmit(onSubmit)}>
        <h5 className={styles["form-subtitle"]}>
          {valueBasedOnCpfOrCnpj(
            "Informações Pessoais",
            "Informações Empresariais"
          )}
        </h5>
        <div className={styles["form-box"]}>
          <FormInputs
            validators={[
              () => {
                ("");
              },
              validateCpfOrCnpj,
              validateEmail,
              validatePhoneNumber,
              () => {
                ("");
              },
              () => {
                ("");
              },
              () => {
                ("");
              },
              () => {
                ("");
              },
              () => {
                ("");
              },
              () => {
                ("");
              },
              () => {
                ("");
              },
            ]}
            isLoading={isLoading}
            labels={[
              valueBasedOnCpfOrCnpj("Nome completo", "Nome da empresa"),
              valueBasedOnCpfOrCnpj("CPF", "CNPJ"),
              "Email",
              "Telefone",
              "CEP",
              "Estado",
              "Cidade",
              "Bairro",
              "Rua",
              "Numero",
              "Complemento",
            ]}
            names={[
              "name",
              "legalId",
              "email",
              "phoneNumber",
              "postalCode",
              "state",
              "city",
              "neighborhood",
              "street",
              "addressNumber",
              "complement",
            ]}
            placeholders={[
              "nome",
              valueBasedOnCpfOrCnpj("000.000.000-00", "00.000.000/0000-00"),
              "example@gmail.com",
              "(99) 9 9999-9999",
              "00000-000",
              `${isLoading ? "..." : "estado"}`,
              `${isLoading ? "..." : "cidade"}`,
              `${isLoading ? "..." : "bairro"}`,
              `${isLoading ? "..." : "rua"}`,
              "numero",
              "complemento",
            ]}
            onChangeHandlers={[
              null,
              valueBasedOnCpfOrCnpj(applyCpfMask, applyCnpjMask),
              null,
              applyPhoneNumberMask,
              postalCodeHandler,
              null,
              null,
              null,
              null,
              null,
              null,
            ]}
            register={register}
            errors={errors}
          />
        </div>

        <button type='submit' className='btn'>
          {isSubmitting ? "Criando conta..." : "Criar conta"}
        </button>
      </form>
      {showModal && (
        <Modal onClose={modalHandler} message='Conta criada com sucesso!' />
      )}
    </div>
  );
}

// DesafioMxM_FrontEnd/src/app/modules/home/components/form/form.component.ts
import { Component, OnInit, DoCheck } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { FormData } from '../../models/FormData';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss'],
})
export class FormComponent implements OnInit {
  public checkboxOptions: Array<string> = ['Pessoa física', 'Pessoa juridica'];

  public formData: Array<FormData> = [
    { label: 'Nome completo', name: 'name', placeholder: 'nome' },
    { label: 'CPF', name: 'legalId', placeholder: '000.000.000-00' },
    { label: 'Email', name: 'email', placeholder: 'example@gmail.com' },
    { label: 'Telefone', name: 'phoneNumber', placeholder: '(99) 9 9999-9999' },
    { label: 'CEP', name: 'postalCode', placeholder: '00000-000' },
    { label: 'Estado', name: 'state', placeholder: 'estado' },
    { label: 'Cidade', name: 'city', placeholder: 'cidade' },
    { label: 'Bairro', name: 'neighborhood', placeholder: 'bairro' },
    { label: 'Rua', name: 'street', placeholder: 'rua' },
    { label: 'Número', name: 'addressNumber', placeholder: 'número' },
    { label: 'Complemento', name: 'complement', placeholder: 'complemento' },
  ];

  public formRegister: FormGroup = this.formBuilder.group({
    type: ['Pessoa física'],
    name: ['', Validators.required],
    legalId: ['', Validators.required],
    email: ['', Validators.required],
    phoneNumber: ['', Validators.required],
    postalCode: ['', Validators.required],
    state: ['', Validators.required],
    city: ['', Validators.required],
    neighborhood: ['', Validators.required],
    street: ['', Validators.required],
    addressNumber: ['', Validators.required],
    complement: [''],
  });

  public showErrors: boolean = false;
  public isLoading: boolean = false;
  public isSubmitting: boolean = false;
  public showModal: boolean = false;

  constructor(private formBuilder: FormBuilder) {}

  ngOnInit(): void {}

  public valueBasedOnCpfOrCnpj(value1: any, value2: any) {
    return this.formRegister.value.type === 'Pessoa física' ? value1 : value2;
  }

  public updateFormData(option: string) {
    console.log(this.formRegister.value);
    if (option === 'Pessoa juridica') {
      this.formData[0].label = 'Nome da empresa';
      this.formData[1].label = 'CNPJ';
      this.formData[1].placeholder = '00.000.000/0000-00';
    } else {
      console.log(this.formData);
      this.formData[0].label = 'Nome completo';
      this.formData[1].label = 'CPF';
      this.formData[1].placeholder = '000.000.000-00';
    }
  }

  public submitForm(): void {
    console.log(this.formRegister.value);
    if (this.formRegister.valid) {
      // console.log(this.formRegister);
      // const headers = {
      //   'Content-Type': 'application/json',
      // };

      // this.http.post(
      //   'https://localhost:7042/users',
      //   JSON.stringify(this.formRegister),
      //   { headers }
      // );

      // data.type = selectedOption;
      // data.legalId = cleanMask(data.legalId);
      // data.phoneNumber = cleanMask(data.phoneNumber);
      // data.postalCode = cleanMask(data.postalCode);
      // console.log(data);
      // this.isSubmitting = true;

      // this.showErrors = false;
      this.formRegister.reset();
    }
    this.showErrors = true;
  }
}

<div class="container">
  <h2 class="title">Cadastro de Usuário</h2>

  <form (submit)="submitForm()" [formGroup]="formRegister">
    <div class="checkbox-group">
      <label *ngFor="let option of checkboxOptions">
        <input
          name="type"
          type="radio"
          (click)="updateFormData(option)"
          value="{{ option }}"
          formControlName="type"
        />
        <span>{{ option }}</span>
      </label>
    </div>
    <h5 class="form-subtitle">
      {{
        valueBasedOnCpfOrCnpj(
          "Informações Pessoais",
          "Informações Empresariais"
        )
      }}
    </h5>

    <div class="form-box">
      <div
        *ngFor="let item of formData"
        class="form-group"
        [ngClass]="{ 'postal-code': item.name === 'postalCode' }"
      >
        <label>{{ item.label }}<span class="error-message">*</span></label>
        <input
          class="form-control"
          type="text"
          formControlName="{{ item.name }}"
          placeholder="{{ item.placeholder }}"
        />
        <p
          *ngIf="showErrors && formRegister.get(item.name)?.errors"
          class="error-message"
        >
          O campo {{ item.label }} é obrigatorio
        </p>
        <h5 *ngIf="item.name === 'email'" class="form-subtitle">
          Informações de Endereço
        </h5>
      </div>
    </div>
    <button type="submit" class="btn" (click)="submitForm()">
      Criar conta
    </button>
  </form>
  <app-modal *ngIf="showModal"></app-modal>
</div>
