// DesafioMxM_FrontEnd/src/app/modules/home/components/user-info/user-info.component.ts
import { Component } from '@angular/core';
import { UserData } from '../../models/UserData';

@Component({
  selector: 'app-user-info',
  templateUrl: './user-info.component.html',
  styleUrls: ['./user-info.component.scss'],
})
export class UserInfoComponent {
  public userData: Array<UserData> = [
    { label: 'Nome Completo', name: '' },
    { label: 'CPF/CNPJ', name: '' },
    { label: 'Email', name: '' },
    { label: 'Telefone', name: '' },
    { label: 'CEP', name: '' },
    { label: 'Estado', name: '' },
    { label: 'Cidade', name: '' },
    { label: 'Bairro', name: '' },
    { label: 'Rua', name: '' },
    { label: 'Número', name: '' },
    { label: 'Complemento', name: '' },
  ];

  constructor() {}
}

<div class="container">
  <h2 class="title">Dados de Usuario</h2>
  <div class="search-box">
    <input class="search-input" placeholder="Digite o id de usuario" />
    <button class="btn-search">Consultar usuario</button>
  </div>

  <!-- <p class="error-message"></p> -->

  <h5>Dados Gerais</h5>
  <div *ngFor="let data of userData" class="user">
    <div class="label">{{ data.label }}</div>
    <div class="value">{{ data.name }}</div>
  </div>
</div>

// DesafioMxM_FrontEnd/src/components/UserInfo/UserInfo.tsx
import axios from "axios";
import { useRef, useState } from "react";
import { UserOutput } from "../UserOutput/UserOutput";
import styles from "./style.module.css";

export function UserInfo() {
  const inputRef = useRef<HTMLInputElement>(null);

  const [userData, setUserData] = useState({
    type: "",
    name: "",
    legalId: "",
    email: "",
    phoneNumber: "",
    postalCode: "",
    state: "",
    city: "",
    neighborhood: "",
    street: "",
    addressNumber: "",
    complement: "",
  });

  async function getUserData() {
    try {
      const id = inputRef.current?.value;
      const { data } = await axios.get(`https://localhost:7042/users/${id}`);
      if (inputRef.current) inputRef.current.value = "";
      setUserData(data);
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div className='container'>
      <h2 className='title'>Dados de Usuario</h2>
      <div className={styles["search-box"]}>
        <input
          className={styles["search-input"]}
          placeholder='Digite o id de usuario'
          ref={inputRef}
        />
        <button className={styles["btn-search"]} onClick={getUserData}>
          Consultar usuario
        </button>
      </div>
      <h5>Dados Gerais</h5>
      <UserOutput
        labels={[
          "Tipo",
          "Nome",
          "CPF/CNPJ",
          "Email",
          "Telefone",
          "CEP",
          "Estado",
          "Cidade",
          "Bairro",
          "Rua",
          "Numero",
          "Complemento",
        ]}
        data={userData}
      />
    </div>
  );
}
